on:
  workflow_dispatch

name: Test bc23
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bc23
        uses: actions/checkout@v3
        with:
          repository: 'ParadigmMC/mcman-bc23'
          path: bc23
      - name: Checkout mcman 0.4
        uses: actions/checkout@v3
        with:
          repository: 'ParadigmMC/mcman'
          ref: 'source-rewrite'
          path: 'mcman'
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install mcman
        run: |
          cargo install --path ${{ github.workspace }}/mcman
      - name: Test the server
        run: |
          mcman run --test
        working-directory: ${{ github.workspace }}/bc23
