on:
  workflow_dispatch

name: Test bc23
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: bc23
      - uses: actions/checkout@v3
        with:
          repository: 'ParadigmMC/mcman'
          ref: 'source-rewrite'
          path: 'mcman'
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo run --manifest-path $GITHUB_WORKSPACE/mcman/Cargo.toml --quiet run --test
        working-directory: $GITHUB_WORKSPACE/bc23
